config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root                   									'static_pages#home'

  get    'manifesto' 									=>  'static_pages#manifesto' 

  get    'shop'      									=>  'shops#index'

  get    'tipjar'    									=>  'tip_jars#index'

  get    'forum'     									=>  'forums#index'

  get    'contact'   									=>  'contacts#new'

  get    'contacts'  									=>  'contacts#new'

  post   'contacts'  									=>  'contacts#create'

  get    'signup'  			  						=>  'users#new'

  post   'signup'   		  						=>  'users#create'

  get    'login'     									=>  'sessions#new'

  post   'login'     									=>  'sessions#create'
  
  delete 'logout'    									=>  'sessions#destroy'

  get    'users/:id' 									=>  'users#show', as: :user

  patch  'users/mod/:id'              =>  'users#mod', as: :mod_user

  patch  'users/unmod/:id'            =>  'users#unmod', as: :unmod_user

  patch  'users/:id'                  =>  'users#ban'

  get    'users/:id/edit'             =>  'users#edit', as: :edit_user

  patch  'users/:id/edit'             =>  'users#update'

  get    '/users'                     =>  'users#index', as: :users

  get    'thankyou'  		  						=>  'static_pages#thanks'

  get    'cancel'   		  						=>  'static_pages#cancel'

  get    'forum/:id/move'             =>  'posts#move', as: :move

  patch  'forum/:id/move'             =>  'posts#move_update'

  get    'forum/:subject' 						=>  'forums#show', as: :subject

  get    'forum/:subject/new' 				=>  'posts#new', as: :new_post

  post   'forum/:subject/new' 				=>  'posts#create'

  get    'forum/:id/edit' 						=>  'posts#edit', as: :edit_post

  get    'forum/:subject/:id' 				=>  'posts#show', as: :post

  patch  'forum/:id/edit' 						=>  'posts#update'

  delete 'forum/:subject/:id'         =>  'posts#destroy'

  get    'forum/:subject/:id/comment' =>  'comments#new', as: :new_comment

  post   'forum/:subject/:id/comment' =>  'comments#create'

  get    'forum/:subject/:id/comment/edit' =>  'comments#edit', as: :edit_comment

  patch  'forum/:subject/:id/comment/edit' =>  'comments#update'

  delete 'forum/:subject/:id/comment' =>  'comments#destroy', as: :delete_comment

  patch  'forum/:id/:sticky/sticky' 	=>  'posts#sticky', as: :sticky_comment

  patch  'forum/:id/:closed/close'    =>  'posts#close', as: :close_comment

  get    'auth/:provider/callback'    => 'sessions#create_omniauth'

  get    'edit/info/:id'              => 'info_blocks#edit', as: :edit_info

  patch  'edit/info/:id'              => 'info_blocks#update'

  resources :account_activations, only: [:edit]

  resources :password_resets,     only: [:new, :create, :edit, :update]


end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController

	def index
	end

	def show
		if params[:subject] == "all"
			@subject = Subject.all
			@forums = Post.order(sticky: :desc, updated_at: :desc).all
		else
			@subject = Subject.find_by_name(params[:subject])
			@forums = Post.where(subject_id: @subject.id).order(sticky: :desc,
												updated_at: :desc).paginate(page: params[:page],
																									  per_page: 10)
		end
	end

	def new
		@subject = params[:subject]
		@post = Post.new
	end

	def create
		@post = Post.new post_params
	end

	private

		def post_params
			params.require(:post).permit(:title, :body, :user_id, :subject_id)
		end

end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/views/forums/_post_item.html.erb
<li class="post">
	<% if current_user && current_user.mod == 1 || current_user == post.user %>
			<div class="btn-group dropup">
			<button type="button" class="btn btn-info btn-xs dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
				<span class="glyphicon glyphicon-cog"></span> <span class="caret"></span>
			</button>
			<ul class="dropdown-menu list-inline">
				<% if current_user == post.user %>
		  		<li><%= link_to "Edit", "/forum/#{post.id}/edit", class: "btn btn-primary" %></li>
		  	<% end %>
	  		<% if current_user && current_user.mod == 1 %>
			  	<li><%= link_to "Sticky", sticky_comment_path(post.id,1), method: :patch, class: "btn btn-success" %></li>
			  	<li><%= link_to "Unsticky", sticky_comment_path(post.id,0), method: :patch, class: "btn btn-warning" %></li>
			  	<li><%= link_to "Move", move_path(post.id), class: "btn btn-success" %></li>
			  	<li><%= link_to "Close", close_comment_path(post.id,1), method: :patch, class: "btn btn-warning" %></li>
			  	<li><%= link_to "Open", close_comment_path(post.id,0), method: :patch, class: "btn btn-success" %></li>
			  <% end %>
			  <li><%= link_to "Delete", post_path(@subject.name,post.id), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger" %></li>
			</ul>
		</div>
	<% else %>
		<div class="filler-block dropup">
			<button class="btn btn-xs">
				
			</button>
		</div>
	<% end %>
	<a class="post-link" href="<%="#{@subject.name}/#{post.id}"%>">
		<div class="container-fluid">	
			<div class="row test">
				<div class="col-md-4 col-sm-3 col-xs-3 test-left">
					<div class="test-wrapper">
						<div class="icons">

							<% if current_user && (post.find_viewing(current_user.id).nil? || post.find_viewing(current_user.id) < post.recent_activity_time)  %>
								<span class="glyphicon glyphicon-eye-open"> </span>
							<% end %>
					  	<% if post.sticky == 1 %>
					  		<span class="glyphicon glyphicon-pushpin"> </span>
					  	<% end %>
					  	<% if post.closed == 1 %>
					  		<span class="glyphicon glyphicon-lock"> </span>
					  	<% end %>
					  </div>
						<p><%= post.title %></p>
					</div>
				</div>
				<div class="col-md-5 col-sm-6 col-xs-6 test-mid">
					<div class="test-wrapper">
						<div class="row">
							<div class="col-xs-4 test-wrapper"><p><%= post.user.name %></p></div>
							<div class="col-xs-4 test-wrapper"><p>Posted: <%= post.created_at.strftime("%-m/%-e/%-y") %></p></div>
							<div class="col-xs-4 test-wrapper"><p>Recent: <%= post.recent_activity_time.strftime("%-m/%-e/%-y") %></p></div>
						</div>
					</div>
				</div>
				<div class="col-sm-2 col-xs-2 test-right">
					<div class="test-wrapper">	
						<p>Comments: <%= post.comments.count %></p>
					</div>
				</div>
			</div>
		</div>
	</a>
</li>

app/views/forums/index.html.erb
<% provide(:title, "Forum") %>
<a href="/forum/all" class="forum">
	<div class="info forum">
		<h1>Forum</h1>
		<h3 class="container-fluid">Ask questions. Be courteous. Be amazing.</h3>
		<h2 class="container-fluid">Click a subject to open the specific forum.</h2>
		<br>
	</div>
</a>

<a href="/forum/content" class="forum">
	<div class="info forum">
		<h1>content</h1>
		<h4 class="container-fluid">All things content related should be posted here. What kind of things will be streamed? Can we expect a specific console or coverage of certain events?</h4>
		<br>
	</div>
</a>

<a href="/forum/technology" class="forum">
	<div class="info forum">
		<h1>technology</h1>
		<h4 class="container-fluid">All things technology, specifically, what it takes to stream! This can be a surprisingly deep subject, so hopefully we can answer all your questions. Feel free to ask questions too!</h4>
		<br>
	</div>
</a>

<a href="/forum/games" class="forum">
	<div class="info forum">
		<h1>Games</h1>
		<h4 class="container-fluid">Have a favorite game? Feel strongly about the plot of said game? Feel nothing because games have numbed you to reality? This is the place for you! All are welcome to talk about any game, just keep it family friendly in there!</h4>
		<br>
	</div>
</a>

<a href="/forum/general" class="forum">
	<div class="info forum">
		<h1>General</h1>
		<h4 class="container-fluid">Have a question, comment, or idea that doesn't fit in the other categories? This is the place to post it!</h4>
		<br>
	</div>
</a>

<a href="/forum/all" class="forum">
	<div class="info forum">
		<h1>all</h1>
		<h4 class="container-fluid">Click here to view all subjects in the forums!</h4>
		<br>
	</div>
</a>

app/views/forums/show.html.erb
<% provide(:title, "Forum") %>
<% if @subject.class == Subject::ActiveRecord_Relation %>	
	<% @subject.each do |s| %>
		<div class="info forum">
			<h1><%=s.name%></h1>
			<br>
			<% @forums.each do |post| %>
				<ul class="posts">
					<% if post.subject == s %>
						<%= render partial: 'forums/post_item', locals: {post: post, subject: @subject} %> 
					<% end %>
				</ul>
			<% end %>
			<%= link_to "Start a Thread", "#{s.name}/new", class: "btn btn-success"  %>
		</div>
	<% end %>
<% else %>
	<div class="info forum">
		<h1><%=@subject.name%></h1>
		<br>

		<div class="paginate">
			<%=will_paginate%>
		</div>

		<% @forums.each do |post| %>
			<ul class="posts">
				<%= render partial: 'forums/post_item', locals: {post: post, subject: @subject} %>
			</ul>
		<% end %>

		<%= link_to "Start a Thread", "#{@subject.name}/new", class: "btn btn-success"  %>
		<%= link_to "All Subjects", "/forum/all", class: "btn btn-primary" %>
		<%= link_to "Back", forum_path, class: "btn btn-info" %>
	</div>

	<div class="paginate paginate-bottom">
		<%=will_paginate%>
	</div>

<% end %>