config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root                   									'static_pages#home'

  get    'manifesto' 									=>  'static_pages#manifesto' 

  get    'shop'      									=>  'shops#index'

  get    'tipjar'    									=>  'tip_jars#index'

  get    'forum'     									=>  'forums#index'

  get    'contact'   									=>  'contacts#new'

  get    'contacts'  									=>  'contacts#new'

  post   'contacts'  									=>  'contacts#create'

  get    'signup'  			  						=>  'users#new'

  post   'signup'   		  						=>  'users#create'

  get    'login'     									=>  'sessions#new'

  post   'login'     									=>  'sessions#create'
  
  delete 'logout'    									=>  'sessions#destroy'

  get    'users/:id' 									=>  'users#show', as: :user

  patch  'users/mod/:id'              =>  'users#mod', as: :mod_user

  patch  'users/unmod/:id'            =>  'users#unmod', as: :unmod_user

  patch  'users/:id'                  =>  'users#ban'

  get    'users/:id/edit'             =>  'users#edit', as: :edit_user

  patch  'users/:id/edit'             =>  'users#update'

  get    '/users'                     =>  'users#index', as: :users

  get    'thankyou'  		  						=>  'static_pages#thanks'

  get    'cancel'   		  						=>  'static_pages#cancel'

  get    'forum/:id/move'             =>  'posts#move', as: :move

  patch  'forum/:id/move'             =>  'posts#move_update'

  get    'forum/:subject' 						=>  'forums#show', as: :subject

  get    'forum/:subject/new' 				=>  'posts#new', as: :new_post

  post   'forum/:subject/new' 				=>  'posts#create'

  get    'forum/:id/edit' 						=>  'posts#edit', as: :edit_post

  get    'forum/:subject/:id' 				=>  'posts#show', as: :post

  patch  'forum/:id/edit' 						=>  'posts#update'

  delete 'forum/:subject/:id'         =>  'posts#destroy'

  get    'forum/:subject/:id/comment' =>  'comments#new', as: :new_comment

  post   'forum/:subject/:id/comment' =>  'comments#create'

  get    'forum/:subject/:id/comment/edit' =>  'comments#edit', as: :edit_comment

  patch  'forum/:subject/:id/comment/edit' =>  'comments#update'

  delete 'forum/:subject/:id/comment' =>  'comments#destroy', as: :delete_comment

  patch  'forum/:id/:sticky/sticky' 	=>  'posts#sticky', as: :sticky_comment

  patch  'forum/:id/:closed/close'    =>  'posts#close', as: :close_comment

  get    'auth/:provider/callback'    => 'sessions#create_omniauth'

  get    'edit/info/:id'              => 'info_blocks#edit', as: :edit_info

  patch  'edit/info/:id'              => 'info_blocks#update'

  resources :account_activations, only: [:edit]

  resources :password_resets,     only: [:new, :create, :edit, :update]


end

app/models/user.rb
class User < ApplicationRecord

	attr_accessor :remember_token, :activation_token, :reset_token
  before_create :create_activation_digest
  #before_update :allow_or_deny_custom_status, if: "custom_status.nil"
  validates :custom_status, length: { maximum: 15 }, uniqueness: { case_sensitive: false }, allow_nil: true
	#before_save { email.downcase! }

	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

	#validates :name,  presence: true, length: {maximum: 50}
	#validates :email, presence: true, length: {maximum: 255},
	#										format: {with: VALID_EMAIL_REGEX},
	#								uniqueness: { case_sensitive: false }
	#validates :password, length: { minimum: 6 }, presence: true, allow_nil: true

	#has_secure_password

  has_many :posts
  has_many :comments
  has_many :contacts

	# Returns a digested hashing of the given string
	def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Saves a remember_digest to the DB
  def remember
  	self.remember_token = User.new_token
  	update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end

  # Creates and assigns the activation token and digest.
  def create_activation_digest
    self.activation_token  = User.new_token
    self.activation_digest = User.digest(activation_token)
  end

  # Activates an account.
  def activate
    update_attribute(:activated,    true)
    update_attribute(:activated_at, Time.zone.now)
  end

  # Sends activation email.
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  # Sets the password reset attributes.
  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest, User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  # Sends password reset email
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  # Returns true if a password reset has expired
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["name"]
      user.email = auth["info"]["email"]
      user.logo = auth["info"]["image"]
    end
  end

  def update_pic(image)
    update_attribute(:logo, image)
  end

  def status
    if custom_status
      custom_status
    elsif owner == 1
      "Owner"
    elsif mod == 1
      "Moderator"
    else
      "Viewer"
    end
  end

  def name_downcase
    name.downcase
  end

  def allow_or_deny_custom_status
    (posts.count + comments.count) >= 15 || owner == 1 || mod == 1 || name.downcase == "mountsafurious"
  end

  def icon
    if name.downcase == "mountsafurious"
      "http://pre12.deviantart.net/b248/th/pre/f/2013/247/e/3/dragon_icon_by_ferocefv-d6krb7y.png"
    elsif owner == 1
      "https://static2.fjcdn.com/comments/It+s+just+some+silly+gifs+no+it+s+a+symbol+of+_048c9c01797436dfc9e96b7e0e2ff793.png"
    elsif mod == 1
      "http://www.iconarchive.com/download/i91290/icons8/windows-8/Military-Sword.ico"
    else
      "http://www.clker.com/cliparts/s/I/Q/p/d/U/black-person-symbol-hi.png"
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		if !logged_in?
			flash[:warning] = "You must be logged in to view a profile"
			redirect_to root_path
		else
			@users = User.where(banned: false).order("LOWER(name)").paginate(page: params[:page])
		end
	end

	def new
		@user = User.new
	end

	def edit
		@user = User.find params[:id]
		@status = @user.status
	end

	def update
		@user = User.find params[:id]
		if current_user && current_user == @user
			if @user.allow_or_deny_custom_status || params[:user][:custom_status] == @user.status || params[:user][:custom_status].empty?
				if params[:user][:custom_status].empty?	
					if @user.update user_params_without_custom_status
						flash[:success] = "Profile updated"
						redirect_to user_path(@user)
					else
						render :edit
					end
				else
					if @user.update user_params
						flash[:success] = "Profile updated"
						redirect_to user_path(@user)
					else
						render :edit
					end
				end
			else
				flash[:danger] = "You must construct additional pylons!"
				render :edit
			end
		else
			flash[:danger] = "You can not edit someone else's profile"
			redirect_to root_url
		end
	end

	def show
		@user = User.find_by_id params[:id]
		#redirect_to root_path and return unless @user.activated?
		if !logged_in?
			flash[:warning] = "You must be logged in to view a profile"
			redirect_to root_url
		end
	end

	def create
		@user = User.new user_params
		@user.mod = 0
		@user.owner = 0
		if @user.save
			@user.send_activation_email
      message = "Please check your email to activate your account."
      message += " This may take a minute, please be patient."
      flash[:info] = message
      redirect_to root_url
		else
			render :new
		end
	end

	def ban
		@user = User.find params[:id]
		if current_user && current_user.mod == 1
			@user.banned = true
			@user.save
			flash[:success] = "#{@user.name} has been banned. PURGE THE REBEL SCUM!"
			redirect_to users_url
		else
			flash[:warning] = "Only mods can ban users."
			redirect_to root_url
		end
	end

	def mod
		@user = User.find params[:id]
		if current_user && current_user.owner == 1
			@user.mod = 1
			@user.save
			flash[:success] = "#{@user.name} has been made a mod"
			redirect_to users_url
		else
			flash[:warning] = "Only the owner can give mod privileges"
			redirect_to root_url
		end
	end

	def unmod
		@user = User.find params[:id]
		if current_user && current_user.owner == 1
			@user.mod = 0
			@user.save
			flash[:success] = "#{@user.name} no longer has mod privileges"
			redirect_to users_url
		else
			flash[:warning] = "Only the owner can remove mod privileges"
			redirect_to root_url
		end
	end

	private

		def user_params
			params.require(:user).permit(:name, :email, :password,
										 :password_confirmation, :public_profile, :custom_status)
		end

		def user_params_without_custom_status
			params.require(:user).permit(:name, :email, :password,
										 :password_confirmation, :public_profile)
		end

end

app/helpers/users_helper.rb
module UsersHelper

	# Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 80 })
    if !user.email.nil?
      gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    else
      gravatar_id = Digest::MD5::hexdigest("noemail@example.com")
    end
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

  def logo_for(user, options = {size: 80})
  	size = options[:size]
  	if user.logo
  		image_tag(user.logo, alt: user.name, size: "#{size}x#{size}",
  																						class: "user-logo")
  	else
  		gravatar_for(user, size: options[:size])
  	end
  end
end

app/views/users/edit.html.erb
<div class="edit-user">	
	<div class="info new-user">
		<p></p>
		<h1>Edit Profile</h1>
		<br>
		<div class="container-fluid">
	    <div class="col-md-6 col-md-offset-3">

	    	<div class="gravatar_edit">
		      <p><%= logo_for @user %>
		      <% if @user.logo.nil? %>	
		      	<a href="http://gravatar.com/emails" target="_blank" rel="noopener">change</a></p>
		      	<a data-toggle="modal" data-target="#myModal" class="pull-left"><span class="glyphicon glyphicon-question-sign about-gravatar"></span></a>
		      <% end %>
						      <!-- Modal -->
					<div id="myModal" class="modal fade" role="dialog">
					  <div class="modal-dialog">

					    <!-- Modal content-->
					    <div class="modal-content">
					      <div class="modal-header">
					        <button type="button" class="close" data-dismiss="modal">&times;</button>
					        <h4 class="modal-title">What is a gravatar</h4>
					      </div>
					      <div class="modal-body">
					        <p>Gravatar stands for Globally Recognized Avatar. It is globally recognized because millions of people and websites use them. Most popular applications like WordPress have built-in support for Gravatar. When a user leaves a comment (with email) on a site that supports Gravatar, it pulls their Globally Recognized Avatar from Gravatar servers. Then that picture is shown next to the comment. This allows each commenter to have their identity through out the world wide web.</p>
					      </div>
					      <div class="modal-footer">
					        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
					      </div>
					    </div>

					  </div>
					</div>
		    </div>
				<%= form_for @user, url: edit_user_path(@user) do |f| %>
					<%= render 'shared/error_messages' %>

				  <%#= f.label :name %>
				  <%#= f.text_field :name, class: 'form-control' %>

				  <%= f.label :email %>
				  <%= f.text_field :email, class: 'form-control' %>
				  <% if  !@user.allow_or_deny_custom_status%>
				  	<%= f.label :custom_status, "Give yourself a cool forum label!\n(#{15-@user.comments.count - @user.posts.count} comments or posts to unlock)" %>
				  <% else %>
				  	<%= f.label :custom_status, "Give yourself a cool forum label!" %>
				  <% end %>
				  <%= f.text_field :custom_status, class: "form-control", value: @status %>

				  <%= f.label :public_profile, class: "checkbox" do %>
				  <%= f.check_box :public_profile %>
				  <span class="check-label">Make my email public</span>
				  <% end %>

					<%#= f.label :password %>
				  <%#= f.password_field :password, class: 'form-control' %>

				  <%#= f.label :password_confirmation, "Confirmation" %>
				  <%#= f.password_field :password_confirmation, class: 'form-control' %>

				  <%= f.submit "Update", class: "btn btn-success" %>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/users/index.html.erb
<div class="info all-users">
	<div class="container-fluid">
		<h1>All users (<%=@users.count%>)</h1>
		<br>
		<%= will_paginate %>

		<ul class="users">
		  <% @users.each do |user| %>
		    <li>
		      <%= logo_for user, size: 50 %>
		      <%= link_to "#{user.name} | #{user.status}", user %>
		      <% if current_user && current_user.owner == 1 && current_user != user %>
		      	<% if user.mod == 0 || user.mod.nil? %>
				    	| <%= link_to "mod", mod_user_path(user), method: :patch %>
				    <% elsif user.mod == 1 %>
				    	| <%= link_to "unmod", unmod_user_path(user), method: :patch %>
				    <% end %>
				  <% end %>
		      <% if current_user && current_user.mod == 1 && current_user != user && user.mod != 1 %>
				    | <%= link_to "ban", user, method: :patch,
				                                  data: { confirm: "You sure?" } %>
				  <% end %>
		    </li>
		  <% end %>
		</ul>

		<%= will_paginate %>
	</div>
</div>

app/views/users/new.html.erb
<div class="info new-user">
	<p></p>
	<h1>Signup</h1>
	<br>
	<div class="container-fluid">
    <div class="col-md-6 col-md-offset-3">
			<%= form_for @user, url: signup_path do |f| %>
				<%= render 'shared/error_messages' %>

			  <%= f.label :name %>
			  <%= f.text_field :name, class: 'form-control' %>

			  <%= f.label :email %>
			  <%= f.text_field :email, class: 'form-control' %>

				<%= f.label :password %>
			  <%= f.password_field :password, class: 'form-control' %>

			  <%= f.label :password_confirmation, "Confirmation" %>
			  <%= f.password_field :password_confirmation, class: 'form-control' %>

			  <%= f.submit "Sign up", class: "btn btn-success" %>
			<% end %>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<div class="info new-user">
	<h1>Profile</h1>
	<br>

		<div class="row">
		  <aside class="col-md-4">
		    <section class="user_info">
		      <h1 class="title">
		        <%= logo_for @user %>
		        <%= @user.name %>
			       <% if current_user && current_user.mod == 1 && current_user != @user %>
					    | <%= link_to "ban", user_path(@user), method: :patch,
					                                  data: { confirm: "You sure?" } %>
					  <% end %>
		      </h1>

		      <div class="user-stats">
			      <%if @user.public_profile%> <p>email: <%= @user.email %></p> <%end%>
			      <p># of posts: <%= @user.posts.count %></p>
			      <p># of comments: <%= @user.comments.count %></p>
			      <p>status: <%= @user.status %><span class="glyphicon <%=@user.icon%>"></span></p></p>
			    </div>
		    </section>
		  </aside>
		</div>
    
</div>