config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root                   									'static_pages#home'

  get    'manifesto' 									=>  'static_pages#manifesto' 

  get    'shop'      									=>  'shops#index'

  get    'tipjar'    									=>  'tip_jars#index'

  get    'forum'     									=>  'forums#index'

  get    'contact'   									=>  'contacts#new'

  get    'contacts'  									=>  'contacts#new'

  post   'contacts'  									=>  'contacts#create'

  get    'signup'  			  						=>  'users#new'

  post   'signup'   		  						=>  'users#create'

  get    'login'     									=>  'sessions#new'

  post   'login'     									=>  'sessions#create'
  
  delete 'logout'    									=>  'sessions#destroy'

  get    'users/:id' 									=>  'users#show', as: :user

  patch  'users/mod/:id'              =>  'users#mod', as: :mod_user

  patch  'users/unmod/:id'            =>  'users#unmod', as: :unmod_user

  patch  'users/:id'                  =>  'users#ban'

  get    'users/:id/edit'             =>  'users#edit', as: :edit_user

  patch  'users/:id/edit'             =>  'users#update'

  get    '/users'                     =>  'users#index', as: :users

  get    'thankyou'  		  						=>  'static_pages#thanks'

  get    'cancel'   		  						=>  'static_pages#cancel'

  get    'forum/:id/move'             =>  'posts#move', as: :move

  patch  'forum/:id/move'             =>  'posts#move_update'

  get    'forum/:subject' 						=>  'forums#show', as: :subject

  get    'forum/:subject/new' 				=>  'posts#new', as: :new_post

  post   'forum/:subject/new' 				=>  'posts#create'

  get    'forum/:id/edit' 						=>  'posts#edit', as: :edit_post

  get    'forum/:subject/:id' 				=>  'posts#show', as: :post

  patch  'forum/:id/edit' 						=>  'posts#update'

  delete 'forum/:subject/:id'         =>  'posts#destroy'

  get    'forum/:subject/:id/comment' =>  'comments#new', as: :new_comment

  post   'forum/:subject/:id/comment' =>  'comments#create'

  get    'forum/:subject/:id/comment/edit' =>  'comments#edit', as: :edit_comment

  patch  'forum/:subject/:id/comment/edit' =>  'comments#update'

  delete 'forum/:subject/:id/comment' =>  'comments#destroy', as: :delete_comment

  patch  'forum/:id/:sticky/sticky' 	=>  'posts#sticky', as: :sticky_comment

  patch  'forum/:id/:closed/close'    =>  'posts#close', as: :close_comment

  get    'auth/:provider/callback'    => 'sessions#create_omniauth'

  get    'edit/info/:id'              => 'info_blocks#edit', as: :edit_info

  patch  'edit/info/:id'              => 'info_blocks#update'

  resources :account_activations, only: [:edit]

  resources :password_resets,     only: [:new, :create, :edit, :update]


end

app/models/post.rb
class Post < ApplicationRecord

	validates :body, :title, presence: true
	validates :title, length: {maximum: 40}


	has_many :comments, dependent: :destroy
	belongs_to :user
	belongs_to :subject

	def find_viewing(uid)
		viewing = Viewing.find_by(post_id: self.id, user_id: uid)
		if !viewing.nil?
			viewing.viewed_at
		else
			nil
		end
	end

	def recent_activity_time
		recent = self
		comments.each do |c|
			recent = c if c.updated_at > recent.updated_at
		end
		recent.updated_at
	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	def show
		@post = Post.find_by_id params[:id]
		@posts = Comment.where(post_id: @post.id).order(:created_at).paginate(page: params[:page],
																									 per_page: 10)
		if logged_in?
			viewing = Viewing.find_or_create_by(user_id: current_user.id,
																					post_id: @post.id)
			viewing.view_now
		end
	end

	def new
		if logged_in?
			@post = Post.new
			@subject = params[:subject]
		else
			flash[:warning] = "You must be logged in to post on the forum"
			redirect_to "/forum/all"
		end
	end

	def create
		if logged_in?	
			@post = Post.new post_params
			@post.user_id = current_user.id
			@post.subject_id = Subject.find_by_name(params[:subject]).id
			if @post.save
				flash[:success] = "New Thread Created"
				redirect_to "/forum/#{params[:subject]}/#{@post.id}"
			else
				render :new
			end
		else
			flash[:warning] = "You must be logged in to post on the forum"
	    redirect_to "/forum/#{params[:subject]}/new"
		end
	end

	def edit
		@post = Post.find_by_id params[:id]
	end

	def update
		@post = Post.find_by_id params[:id]
		if current_user == @post.user || current_user.mod == 1
			if @post.closed == 1
				flash[:warning] = "This thread is closed and can not be edited"
				redirect_to "/forum/all"
			elsif @post.update post_params
				flash[:success] = "Updated"
				redirect_to "/forum/#{@post.subject.name}/#{@post.id}"
			else
				render :edit
			end
		else
			flash[:warning] = "You may only edit your own threads!"
			redirect_to forum_path
		end
	end

	def destroy
		@post = Post.find(params[:id])
		if current_user == @post.user || current_user.mod == 1
	    flash[:success] = "Thread has been deleted!"
	    @post.destroy
	  else
	  	flash[:warning] = "You may only delete your own threads!"
	  end
    redirect_to "/forum/all"
	end

	def sticky
		if current_user.mod == 1
			post = Post.find params[:id]
			post.sticky = params[:sticky]
			post.save
			flash[:success] = ((post.sticky == 1) ? "Ewwww, why is this thread all sticky?" : "This thread is no longer sticky")
		else
			flash[:warning] = "Only mods can make threads sticky"
		end
		redirect_to "/forum/all"
	end

	def move
		@post = Post.find params[:id]
		@subjects = Subject.all
	end

	def move_update
		if current_user.mod == 1	
			@post = Post.find params[:id]
			@post.subject = Subject.find_by_name params[:post][:subject]
			@post.save
			flash[:success] = "Thread has been moved"
		else
			flash[:warning] = "Only mods can move threads"
		end
		redirect_to "/forum/all"
	end

	def close
		if current_user.mod == 1
			post = Post.find params[:id]
			update_save = post.updated_at
			post.closed = params[:closed]
			post.save
			post.updated_at = update_save
			post.save
			flash[:success] = ((post.closed == 1) ? "Post closed" : "Post opened")
		else
			flash[:warning] = "Only mods can close or open posts"
		end
		redirect_to "/forum/all"
	end

	private

		def post_params
			params.require(:post).permit(:title,:body)
		end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<% provide(:title, "Edit Post") %>
<div class="info new-post">
	<p></p>
	<h1>Edit Thread</h1>
	<br>
	<div class="container-fluid">
    <div class="col-md-6 col-md-offset-3">
			<%= form_for @post, url: edit_post_path do |f| %>
				<%= render 'shared/error_messages_posts' %>

			  <%= f.label :title %>
			  <%= f.text_field :title, class: 'form-control' %>

			  <%= f.label :body %>
			  <%= f.text_area :body, class: 'form-control' %>

			  <%= f.submit "Update", class: "btn btn-success" %>
			  <%= link_to "Back", "/forum/all", class: "btn btn-primary" %>
			<% end %>
		</div>
	</div>
</div>

app/views/posts/move.html.erb
<% provide(:title, "Move Post") %>
<div class="info move-post">
	<p></p>
	<h1>Move Thread</h1>
	<br>
	<div class="container-fluid">
    <div class="col-md-6 col-md-offset-3">
			<%= form_for @post, url: move_path(@post.id) do |f| %>
				<%= select("post", "subject", @subjects.collect {|s| [ s.name ] }) %>
			  <%= f.submit "Move", class: "btn btn-success" %>
			  <%= link_to "Back", "/forum/all", class: "btn btn-primary" %>
			<% end %>
		</div>
	</div>
</div>

app/views/posts/new.html.erb
<% provide(:title, "New Post") %>
<div class="info new-post">
	<p></p>
	<h1>New Thread - <%=@subject%></h1>
	<br>
	<div class="container-fluid">
    <div class="col-md-6 col-md-offset-3">
			<%= form_for @post, url: new_post_path do |f| %>
				<%= render 'shared/error_messages_posts' %>

			  <%= f.label :title %>
			  <%= f.text_field :title, class: 'form-control' %>

			  <%= f.label :body %>
			  <%= f.text_area :body, class: 'form-control' %>

			  <%= f.submit "Post", class: "btn btn-success" %>
			  <%= link_to "Back", "/forum/all", class: "btn btn-primary" %>
			<% end %>
		</div>
	</div>
</div>

app/views/posts/show.html.erb
<% provide(:title, "Forum") %>
<div class="post-show">	
	<div class="info view-post container-fluid">
		<div class="row">
			<div class="row-height">
				<div class="col-md-4 col-height user-info post-info">
					<div class="inside">
						<div class="content">
							<div class="tool-buttons">
								<% if current_user %>
									<% if current_user.mod == 1 || current_user == @post.user %>
							  		<% if current_user == @post.user%>
							  			<%= link_to "Edit", "/forum/#{@post.id}/edit", class: "btn btn-primary" %>
							  		<% end %>
								  	<%= link_to "Delete", post_path(@post.id), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger" %>
							  	<% end %>
							  <% end %>
			  			</div>
							<p><%= logo_for @post.user %></p>
							<p><%= link_to @post.user.name, user_path(@post.user) %></p>
							<p><%= @post.user.status %>  <%= image_tag @post.user.icon, class: "user-icon" %></p>
							<p>Joined: <%=@post.user.created_at.strftime("%-m/%-d/%-y")%></p>
							<p>Posted: <%=@post.created_at.strftime("%-m/%-d/%-y")%></p>
						</div>
					</div>
				</div>
				<div class="col-md-8 col-height post-body">
					<div class="inside">
						<div class="content">
							<h1><%= @post.title %></h1>
							<p><%= auto_link(simple_format(@post.body)) %></p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

	<%= link_to "Comment", new_comment_path, class: "btn btn-success" %>
	<%= link_to "Back", "/forum/#{@post.subject.name}", class: "btn btn-primary" %>

	<div class="paginate">
		<%=will_paginate%>
	</div>
		<% @posts.each do |c| %>
			<div class="info comment container-fluid">
				<div class="row">
					<div class="row-height">
						<div class="col-md-4 col-height user-info post-info">
							<div class="inside">
								<div class="content">
									<div class="tool-buttons">
										<% if current_user %>
											<% if current_user.mod == 1 || current_user == c.user %>
									  		<% if current_user == c.user%>
									  			<%= link_to "Edit", edit_comment_path(@post.subject.name,c.id), class: "btn btn-primary" %>
									  		<% end %>
										  	<%= link_to "Delete", delete_comment_path(@post.subject.name,c.id), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger" %>
									  	<% end %>
									  <% end %>
					  			</div>
									<p><%= logo_for c.user %></p>
									<p><%= link_to c.user.name, user_path(c.user) %></p>
									<p><%= c.user.status %> <%= image_tag c.user.icon, class: "user-icon" %></p>
									<p>Joined: <%=c.user.created_at.strftime("%-m/%-e/%-y")%></p>
									<p>Posted: <%=c.created_at.strftime("%-m/%-e/%-y, %l:%M %p")%></p>
									<% if c.updated_at != c.created_at %>
										<p>Edited: <%=c.updated_at.strftime("%-m/%-e/%-y, %l:%M %p")%></p>
									<% end %>
								</div>
							</div>
						</div>
						<div class="col-md-8 col-height comment-body">
							<div class="inside">
								<div class="content">
									<p><%= auto_link(simple_format(c.body)) %></p>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		<% end %>
	<div class="paginate paginate-bottom">
		<%=will_paginate%>
	</div>
	<% if @posts.count >= 3 %>
		<%= link_to "Comment", new_comment_path, class: "btn btn-success" %>
		<%= link_to "Back", "/forum/#{@post.subject.name}", class: "btn btn-primary" %>
	<% end %>
</div>