config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root                   									'static_pages#home'

  get    'manifesto' 									=>  'static_pages#manifesto' 

  get    'shop'      									=>  'shops#index'

  get    'tipjar'    									=>  'tip_jars#index'

  get    'forum'     									=>  'forums#index'

  get    'contact'   									=>  'contacts#new'

  get    'contacts'  									=>  'contacts#new'

  post   'contacts'  									=>  'contacts#create'

  get    'signup'  			  						=>  'users#new'

  post   'signup'   		  						=>  'users#create'

  get    'login'     									=>  'sessions#new'

  post   'login'     									=>  'sessions#create'
  
  delete 'logout'    									=>  'sessions#destroy'

  get    'users/:id' 									=>  'users#show', as: :user

  patch  'users/mod/:id'              =>  'users#mod', as: :mod_user

  patch  'users/unmod/:id'            =>  'users#unmod', as: :unmod_user

  patch  'users/:id'                  =>  'users#ban'

  get    'users/:id/edit'             =>  'users#edit', as: :edit_user

  patch  'users/:id/edit'             =>  'users#update'

  get    '/users'                     =>  'users#index', as: :users

  get    'thankyou'  		  						=>  'static_pages#thanks'

  get    'cancel'   		  						=>  'static_pages#cancel'

  get    'forum/:id/move'             =>  'posts#move', as: :move

  patch  'forum/:id/move'             =>  'posts#move_update'

  get    'forum/:subject' 						=>  'forums#show', as: :subject

  get    'forum/:subject/new' 				=>  'posts#new', as: :new_post

  post   'forum/:subject/new' 				=>  'posts#create'

  get    'forum/:id/edit' 						=>  'posts#edit', as: :edit_post

  get    'forum/:subject/:id' 				=>  'posts#show', as: :post

  patch  'forum/:id/edit' 						=>  'posts#update'

  delete 'forum/:subject/:id'         =>  'posts#destroy'

  get    'forum/:subject/:id/comment' =>  'comments#new', as: :new_comment

  post   'forum/:subject/:id/comment' =>  'comments#create'

  get    'forum/:subject/:id/comment/edit' =>  'comments#edit', as: :edit_comment

  patch  'forum/:subject/:id/comment/edit' =>  'comments#update'

  delete 'forum/:subject/:id/comment' =>  'comments#destroy', as: :delete_comment

  patch  'forum/:id/:sticky/sticky' 	=>  'posts#sticky', as: :sticky_comment

  patch  'forum/:id/:closed/close'    =>  'posts#close', as: :close_comment

  get    'auth/:provider/callback'    => 'sessions#create_omniauth'

  get    'edit/info/:id'              => 'info_blocks#edit', as: :edit_info

  patch  'edit/info/:id'              => 'info_blocks#update'

  resources :account_activations, only: [:edit]

  resources :password_resets,     only: [:new, :create, :edit, :update]


end

app/views/layouts/_contact_form.html.erb
<%= form_for(@user, url: contact_path) do |f| %>
	<%= render 'shared/error_messages' %>

  <%= f.label :email %>
  <%= f.text_area :body, class: 'form-control' %>

  <%= f.submit "Send Message", class: "btn btn-primary" %>
<% end %>

app/views/layouts/_flash.html.erb
<% flash.each do |type, message| %>
	<div class="flash alert-<%=type%>"><h3><%=message%></h3></div>	
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small class="inline">
    <p>This website powered and created by <a href="http://martinsafer.com" target="_blank">Martin Safer</a></p>
  
    <div class="center inline">&#169; Vezley 2016</div>
    <nav>
      <ul>
        <li><%= link_to "Contact", contact_path %></li>
      </ul>
    </nav>
  </small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Vezzelution - beta", root_path, id: "logo" %>
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
        data-target=".navbar-collapse">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
    		</button>
    	</div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Contact", contact_path %></li>
        <li><%= link_to "Manifesto", manifesto_path %></li>
        <li><%= link_to "Shop", shop_path %></li>
        <li><%= link_to "Tipjar", tipjar_path %></li>
        <li><%= link_to "Forum", forum_path %></li>
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to current_user.name, '#', class: "profile-name" %></li>
              <li class="divider"></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li><%= link_to "Users", users_path %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", Rails.env.development? ? login_path : '/auth/twitch' %></li>
        <% end %>
      </ul>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield :title %></title>
    <link rel="shortcut icon" href=<%= vezley_logo %> />
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  </head>

  <body>
  	<div class="container">
      <%= render 'layouts/flash' %>
  		<%= render 'layouts/header' %> 
    	<div class="content"><%= yield %></div>
    	<%= render 'layouts/footer' %>
  	</div>
  </body>
</html>